SERVER-NAME: "server1"
SERVER-REGION: "NA"

# Regional Network Configuration
# This system handles cross-proxy transfers automatically.
# - If the target server is in the same region, a standard 'Connect' message is used.
# - If the target is in a different region, a 'TransferPacket' is sent to the target Proxy IP.
NETWORK:
  REGIONS:
    NA:
      PROXY-IP: "na.hugster.net"
      PROXY-PORT: 25565
      SERVERS:
        - "server1"
        - "server2"
        - "end-1"
    EU:
      PROXY-IP: "eu.hugster.net"
      PROXY-PORT: 25565
      SERVERS:
        - "server1-EU"
        - "server2-EU"
        - "end-1-EU"
    AS:
      PROXY-IP: "as.hugster.net"
      PROXY-PORT: 25565
      SERVERS:
        - "server1-AS"
        - "server2-AS"
        - "end-1-AS"

BORDERS:
  ENABLED: false
  CENTER-X: 0.0
  CENTER-Z: 0.0
  COOLDOWN-SECONDS: 5
  COOLDOWN-BARRIER: true
  LIST:
    border-east:
      WORLD: "world"
      SIDE: "EAST"
      COORDINATE: 50000
      TARGET-SERVER: "server2"
    border-west:
      WORLD: "world"
      SIDE: "WEST"
      COORDINATE: -50000
      TARGET-SERVER: "server2"
    border-north:
      WORLD: "world"
      SIDE: "NORTH"
      COORDINATE: -50000
      TARGET-SERVER: "server2"
    border-south:
      WORLD: "world"
      SIDE: "SOUTH"
      COORDINATE: 50000
      TARGET-SERVER: "server2"

PORTALS:
  END-SERVER: "end-1"
  NETHER-SERVER: "server2"
  NETHER-ROUTES:
    route1:
      TARGET-SERVER: "server2"
      CENTER-X: 250
      CENTER-Z: -250
      RADIUS: 250

SETTINGS:
  SYNC:
    MASTER: true # Set to true on only ONE server to sync time/weather
  WORTH-DEFAULT-VALUE: 1.0

KEY-ALL:
  ENABLED: true
  EVERY: 60 # In minutes
  COMMAND: "keymanager give %player% common 1"
  MESSAGE:
    - ""
    - "&#00A4FCʏᴏᴜ ᴊᴜѕᴛ ɢᴏᴛ &21 ᴄᴏᴍᴍᴏɴ &#00A4FCᴋᴇʏ"
    - "&#00A4FC[CLICK TO TELEPORT] &for type /warp crates to open it"
    - ""

SHARDS:
  EVERY: 1 # In minutes
  AMOUNT: 1 # shards
  EVERYWHERE:
    ENABLED: true
    EVERY: 3
    AMOUNT: 1
    EXCLUDED-WORLDS:
      - "duels"
  BOOSTER-MULTIPLIER: 4 # Amethyst Potion

RTP-ZONE:
  ENABLED: true
  EVERY: 30
  TARGET-SERVER: "server2"
  TARGET-WORLD: "world"
  MIN-RADIUS: 500
  MAX-RADIUS: 2000
  CENTER-X: 0
  CENTER-Z: 0
  TITLE: "&#FC0000ʀᴛᴘ ᴢᴏɴᴇ"
  SUB-TITLE: "&fTeleporting in%countdown%"

CHAT-FORMAT:
  ENABLED: true
  CHAT: "&f%prefix%%player%&7: &f%message%"
  HOVER-LORE:
    - "%prefix%%player%"
    - "&7&m----------"
    - "&#00FC00&l$ &fᴍᴏɴᴇʏ &#00FC00%money%"
    - "&#FC0000⚔ &fᴋɪʟʟѕ &#FC0000%kills%"
    - "&#FCE300⌚ &fᴘʟᴀʏᴛɪᴍᴇ &#FCE300%playtime%"
    - "&#F97603☠ &fᴅᴇᴀᴛʜѕ &#F97603%deaths%"
    - "&#A303F9★ &fѕʜᴀʀᴅѕ &#A303F9%shards%"
    - "&7&m----------"
    - "&7ᴄʟɪᴄᴋ ᴛᴏ ᴠɪᴇᴡ ѕᴛᴀᴛѕ"

# Lunar client modules
LUNAR-CLIENT:
  RICH-PRESENCE:
    ENABLED: true
    UPDATE: 1 # In minutes
    PLAYER-STATE: "Playing"
    GAME-STATE: "Playing"
    GAME-NAME: "Economy"
    VARIANT: "%voyager_username% ($%voyager_nicestMoney%)"
    WORLD-NAME: "Economy"
  TEAM-VIEW:
    ENABLED: true
    UPDATE: 20 # In ticks: 20 = 1 sec

COMBAT-MANAGER:
  ENABLED: true
  COOLDOWN: 16 # In seconds
  ACTION-BAR: "&fCombat: &b{time}s"
  # Get combat on:
  ENDER-CRYSTAL: true
  ENDER-PEARL: true
  RESPAWN-ANCHOR: true
  BLOCK-MESSAGE: "&cYou can't use this command in your current status."
  BLOCK-COMMANDS:
    - "/spawn"
    - "/afk"
    - "/rtp"
    - "/homes"
    - "/tpa"
  EXCLUDED-WORLDS:
    - "duels"

AMETHYST-TOOLS:
  EXCLUDED-WORLDS:
    - "duels"
  PICKAXE:
    PARTICLE:
      NAME: "FALLING_DUST"
      MATERIAL: "PURPLE_CONCRETE_POWDER"
      AMOUNT: 10
    DISABLED-BLOCKS:
      - "GRASS_BLOCK"
      - "DIRT_PATH"
      - "DIRT"
      - "COARSE_DIRT"
      - "ROOTED_DIRT"
      - "CLAY"
      - "FARMLAND"
      - "SAND"
      - "RED_SAND"
      - "GRAVEL"
      - "SPAWNER"
    NAME: "&#A303F9ᴀᴍᴇᴛʜʏѕᴛ ᴅʀɪʟʟ"
    LORE:
      - "&79 Blocks Per Break"
      - "&8Self Destruct"
      - "&8{time}"
    ENCHANTMENTS:
      - "MENDING:1"
      - "EFFICIENCY:5"
      - "UNBREAKING:3"
  AXE:
    PARTICLE:
      NAME: "FALLING_DUST"
      MATERIAL: "PURPLE_CONCRETE_POWDER"
      AMOUNT: 10
    NAME: "&#A303F9ᴀᴍᴇᴛʜʏѕᴛ ᴛʀᴇᴇ ᴄʜᴏᴘᴘᴇʀ"
    LORE:
      - "&7Breaks Trees Instantly"
      - "&8Self Destruct"
      - "&8{time}"
    ENCHANTMENTS:
      - "MENDING:1"
      - "EFFICIENCY:5"
      - "UNBREAKING:3"
      - "SILK_TOUCH:1"
  SELLAXE:
    PARTICLE:
      NAME: "FALLING_DUST"
      MATERIAL: "PURPLE_CONCRETE_POWDER"
      AMOUNT: 10
    NAME: "&#A303F9ᴀᴍᴇᴛʜʏѕᴛ ѕᴇʟʟ ᴀxᴇ"
    LORE:
      - "&7Instantly Sells All Items in A Chest"
      - "&8Self Destruct"
      - "&8{time}"
    ENCHANTMENTS:
      - "MENDING:1"
      - "EFFICIENCY:5"
      - "UNBREAKING:3"
  SHOVEL:
    PARTICLE:
      NAME: "FALLING_DUST"
      MATERIAL: "PURPLE_CONCRETE_POWDER"
      AMOUNT: 10
    ALLOWED-BLOCKS:
      - "GRASS_BLOCK"
      - "DIRT_PATH"
      - "DIRT"
      - "COARSE_DIRT"
      - "ROOTED_DIRT"
      - "CLAY"
      - "FARMLAND"
      - "SAND"
      - "RED_SAND"
      - "GRAVEL"
    NAME: "&#A303F9ᴀᴍᴇᴛʜʏѕᴛ ѕʜᴏᴠᴇʟ"
    LORE:
      - "&79 Blocks Per Break"
      - "&8Self Destruct"
      - "&8{time}"
    ENCHANTMENTS:
      - "MENDING:1"
      - "EFFICIENCY:5"
      - "UNBREAKING:3"
  BUCKET:
    PARTICLE:
      NAME: "FALLING_DUST"
      MATERIAL: "PURPLE_CONCRETE_POWDER"
      AMOUNT: 10
    NAME: "&#A303F9ᴀᴍᴇᴛʜʏѕᴛ ʙᴜᴄᴋᴇᴛ"
    LORE:
      - "&7Drains 27 Water At Once"
      - "&8Self Destruct"
      - "&8{time}"
    ENCHANTMENTS: []
  BOOSTER:
    PARTICLE:
      NAME: "FALLING_DUST"
      MATERIAL: "PURPLE_CONCRETE_POWDER"
      AMOUNT: 10
    NAME: "&#A303F9ѕʜᴀʀᴅ ʙᴏᴏѕᴛᴇʀ"
    LORE:
      - "&74x Shard Production for 24 hours"
      - "&8Self Destruct"
      - "&8{time}"
    ENCHANTMENTS: []
