DATABASE: SQLITE

MONGODB:
  URI: ""
  ADDRESS: 127.0.0.1
  PORT: 27017
  DATABASE: Economy
  AUTHENTICATION:
    ENABLED: false
    USERNAME: admin
    PASSWORD: pass
    DATABASE: admin

MYSQL:
  HOST: 127.0.0.1
  PORT: 3306
  DATABASE: economy
  USER: root
  PASSWORD: ""
  PARAMS: useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC

SQLITE:
  FILE: plugins/Economy/data/economy.db