STORAGE_TYPE: "MONGO" # Options: MONGO, MYSQL

MONGO:
  URI: "mongodb://localhost:27017"
  DATABASE: "voyager"

MYSQL:
  HOST: "localhost"
  PORT: 3306
  DATABASE: "voyager"
  USERNAME: "root"
  PASSWORD: ""
  USE_SSL: false

REDIS:
  HOST: "localhost"
  PORT: 6379
  PASSWORD: ""
