main: me.pi3ro.cuy.CuyPlugin
name: Cuy
version: 3.0
api-version: 1.20
author: Pi3ro
folia-supported: true

depend:
  - Vault
  - packetevents

libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:2.2.10
  - org.jetbrains.kotlin:kotlin-reflect:2.2.10
  - io.github.revxrsal:lamp.common:4.0.0-rc.12
  - io.github.revxrsal:lamp.bukkit:4.0.0-rc.12
  - org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.10.2
  - com.cjcrafter:foliascheduler:0.6.3
  - org.mongodb:mongodb-driver-sync:4.7.0
  - org.jetbrains.kotlinx:kotlinx-serialization-json:1.8.0
  - org.json:json:20231013
  - org.apache.httpcomponents:httpclient:4.5.13
  - redis.clients:jedis:5.1.0
  - org.jetbrains.exposed:exposed-core:1.0.0-rc-1
  - org.jetbrains.exposed:exposed-dao:1.0.0-rc-1
  - org.jetbrains.exposed:exposed-jdbc:1.0.0-rc-1
  - com.zaxxer:HikariCP:5.1.0
  - com.github.ben-manes.caffeine:caffeine:3.1.8
  - com.mysql:mysql-connector-j:8.3.0
  - org.xerial:sqlite-jdbc:3.46.0.0